##
#    @mainpage Systems Optimization exercise
#
#    @authors                 Basian Lesi
#    @authors                 Olga Athanasopoulou
#    @authors                 Nathaniel Stephen Frost Hartwig
#    @authors                 Matej Poljuha

import networkx as nx
import sys
import os
import math
from matplotlib import pyplot as plt
from inputData import *
from simulated_Annealing import *
from output_xml import *
from worst_case_delay import *


## Creates a graph from the input data.
#
#   @param tsn_object           TSN object (input data saved in classes)
#
# @return graph, names - two different versions of the graph, visual difference
def createGraph(tsn_object):
    graph = nx.DiGraph()
    names = nx.DiGraph()

    for device in tsn_object.devices:
        graph.add_node(device)
        names.add_node(device.name)

    for link in tsn_object.links:
        graph.add_edge(link.src, link.dest)
        names.add_edge(link.src.name, link.dest.name)
    graph.edges()
    return graph, names

## Finds all possible routes for all streams and constructs an initial solution.
#
#   @param tsn_object           TSN object (input data saved in classes)
#
# @return Nothing.
def findStreamsRoutes(tsn):
    for stream in tsn.streams:
        stream.findRoutes(G)
        stream.initial_solution()

## Prints stream routes.
#
#   @param tsn_object           TSN object (input data saved in classes)
#
# @return Nothing.
def printStreamRoutes(tsn):
    for stream in tsn.streams:
        print("\n\n", stream.id, " rl = ", stream.rl)
        i = 0
        for route in stream.routes:
            i = i + 1
            print("\n", i, " route")
            for r in route:
                print(r.name, end=" ")

## Creates a graph image.
#
#   @param graph               graph object generated by createGraph()
#
# @return Nothing.
def generateGraphImage(graph):
    plt.tight_layout()
    pos = nx.spectral_layout(graph)
    nx.draw_networkx(graph, arrows=True, font_size=6, pos = pos, font_color = 'w', arrowsize=6)
    plt.savefig("images/Graph_Image.png", format="PNG")
    plt.clf()

## Prints solution.
#
#   @param tsn_object           TSN object (input data saved in classes)
#
# @return Nothing.
def printSolution(tsn):
    for s in tsn.streams:
        s.printRouteLinks(tsn)

## Parse the filename imput.
#
#   @param args           filename argument
#
# @return filename
def parsing_input(args):
    folderPath = "test_cases/"

    if not args:
        args.append("TC5_large1.xml")
        filename = folderPath + args[0]
    else:
        filename = folderPath + args[0]
    
    if os.path.exists(filename):
        return filename
    else:
        sys.exit("\33[91mWrong file argument enter one of these: \33[93m \nTC0_example.xml \nTC1_check_red.xml \nTC2_check_bw.xml  \nTC3_medium.xml \nTC3_extended.xml  \nTC5_large1.xml \nTC6_large2.xml \nTC7_huge.xml \33[0m")
    return filename


filename = parsing_input(sys.argv[1:])

tsn = TSN(filename)         # create tsn object

G, N = createGraph(tsn)     # createGraph(tsn) returns two graphs, one with device objects as nodes
                            # and one with device objects names as nodes

findStreamsRoutes(tsn)      # we find for each stream the possible routes and create our initial solution

generateGraphImage(N)       # generate graph image with input only the devices names

simulated_annealing(tsn)    # run simulated annealing algorithm

outputSolutionXML(tsn, filename)  # output results to xml file

